"""One-off backfill: generate analytics snapshots for shows archived BEFORE
RFC 0013's archive-triggered generation existed.

Archiving a show now calls ``generate_show_analytics`` automatically
(``routers/admin/analytics.py::archive_show``), so every show archived going
forward gets a snapshot the moment it stops changing. This script is for the
gap behind that: every show archived before this shipped has no stored
``ShowAnalyticsSnapshot`` at all, and the Shows tab will keep reading 0 for
them until one is generated — no sync will revisit them, because nothing else
calls ``generate_show_analytics`` unattended.

    cd backend
    ../.venv/Scripts/python.exe scripts/backfill_show_analytics.py            # DRY RUN
    ../.venv/Scripts/python.exe scripts/backfill_show_analytics.py --execute

Call the venv interpreter explicitly — see CLAUDE.md > Test Commands for why a
bare ``python`` fails here.

**A DRY RUN IS THE DEFAULT.** Nothing is written without ``--execute``; the dry
run prints every show it would generate a snapshot for.

Only archived shows with NO existing snapshot are touched. A show that already
has one (generated by hand, or re-archived after this shipped) is left alone —
this is a gap-filler, not a resync, and re-computing an existing snapshot could
silently overwrite one a human regenerated deliberately after a correction.
"""

from __future__ import annotations

import argparse

from merlins_collection.config import settings
from merlins_collection.routers.admin.analytics import generate_show_analytics
from merlins_collection.services.dynamodb import InventoryRepository


def find_shows_needing_backfill(repo: InventoryRepository) -> list[str]:
    """Archived shows with no stored snapshot, in list order."""
    return [
        s.show_id for s in repo.list_shows()
        if s.archived and repo.get_show_analytics(s.show_id) is None
    ]


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--table", default=settings.dynamodb_table_name,
                        help="DynamoDB table to read/write (default: %(default)s)")
    parser.add_argument("--region", default=settings.aws_region,
                        help="AWS region (default: %(default)s)")
    parser.add_argument("--execute", action="store_true",
                        help="actually write. WITHOUT THIS FLAG NOTHING IS WRITTEN.")
    return parser


def main(argv=None) -> dict:
    args = _parser().parse_args(argv)
    repo = InventoryRepository(args.table, region_name=args.region)

    mode = "EXECUTE" if args.execute else "DRY RUN — nothing will be written"
    print(f"{args.table} ({args.region}) — {mode}")

    show_ids = find_shows_needing_backfill(repo)
    for show_id in show_ids:
        print(f"  {show_id}")

    generated = 0
    if args.execute:
        for show_id in show_ids:
            generate_show_analytics(show_id, repo=repo)
            generated += 1

    summary = {"shows_needing_backfill": len(show_ids), "shows_generated": generated,
               "executed": bool(args.execute)}
    print(f"\n{summary}")
    if not args.execute and show_ids:
        print("re-run with --execute to generate these snapshots.")
    return summary


if __name__ == "__main__":
    main()
